### ISSUE TITLE
no such file to load -- commander/import (LoadError)

### ISSUE THREAD

**Issue by mmcc** [tj/commander#40]
When I initialize a new commander on my machine, everything works flawlessly. However, when I try to use that script on another developer's machine, I always get this error:

```
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- commander/import (LoadError)
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from ./plx.rb:4
```

What am I missing? My exact flow is, initialize, make a simple commander file, push to git repo, clone that repo on another machine and then try to run that script. I've also verified that the commander gem is installed on the new machine. Thanks in advance for any help and for an amazing tool!

**Comment by santoshrb** [comment]
please check your gemfile and gemfile.lock...
