### ISSUE TITLE
Ruby warning: circular require considered harmful

### ISSUE THREAD

**Issue by ralfclaassens** [tj/commander#84]
The warning below shows that there is something wrong in the way of 'require' in this commander-gem. Would be nice to clean this up.

    ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /.gem/gems/commander-4.2.1/lib/commander.rb
	from packager:23:in  `<main>'
	from packager:23:in  `load'
	from /.gem/gems/packaging-1.1.1.pre/bin/packager:3:in  `<top (required)>'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /.gem/gems/packaging-1.1.1.pre/lib/generator_command.rb:3:in  `<top (required)>'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from .gem/gems/commander-4.2.1/lib/commander.rb:33:in  `<top (required)>'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /.gem/gems/commander-4.2.1/lib/commander/methods.rb:1:in  `<top (required)>'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
	from /ruby/2.1.1/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require

**Comment by ggilder** [comment]
Linking https://github.com/tj/commander/pull/87
