### ISSUE TITLE
--help should display the command flags/options of the default command

### ISSUE THREAD

**Issue by KrauseFx** [tj/commander#89]
I use the following code
```ruby
    command :run do |c|
      c.syntax = 'deliver'
      c.description = 'Run a deploy process using the Deliverfile in the current folder'
      c.option '--force', 'Runs a deployment without verifying any information (PDF file). This can be used for build servers.'
      c.option '--beta', 'Runs a deployment to beta build on iTunes Connect'
      c.option '--skip-deploy', 'Skips deployment on iTunes Connect'
      c.action do |args, options|
        ...
      end
    end

    default_command :run
```

When running `deliver --help`, it will only show the global options (which probably makes sense in some use cases), but I'd prefer to display the options for the default command.

**Comment by KrauseFx** [comment]
I switched to using `global_option` instead, but that's not 100% correct, since I also have a second command `deliver init`, which is used only once for setting up the tool.

**Comment by ggilder** [comment]
I could see that as a possible enhancement but I'm not sure it should be default behavior. If you'd like to put together a pull request for that we can definitely add it!
