### ISSUE TITLE
Option parsing error (incomplete option name)

### ISSUE THREAD

**Issue by d-ash** [tj/commander#93]
Passing only a *beginning* of a name triggers the option to be set.

For example, if --vagrant option is declared, passing --v or --va... to the script, works as if the full name has been passed.

However, global options work correctly (--v is not equivalent to --vagrant)

**Comment by d-ash** [comment]
It seems that the problem is in OptionParser, and it's an old issue.
Could this be corrected within Commander code?

**Comment by ggilder** [comment]
Do you have a link to the issue in OptionParser? I would like to understand why it hasn't been fixed there.

**Comment by d-ash** [comment]
https://www.ruby-forum.com/topic/143551
http://stackoverflow.com/questions/20654065/how-do-i-get-only-long-options-work-in-optionparser-in-ruby
I'd agree with the point that this behaviour is potentially dangerous. Options of CLI tools are very important part of UI, and they have to be processed rigorously, without any guessing and auto-completion.

**Comment by ggilder** [comment]
This issue was moved to commander-rb/commander#6
