### ISSUE TITLE
Default help formatter hard limits command length to 20 characters

### ISSUE THREAD

**Issue by jszwedko** [tj/commander#98]
It would be nice if this was instead based on the length of the longest command or was configurable.

https://github.com/tj/commander/blob/master/lib/commander/help_formatters/terminal/help.erb#L12

@stephenchu

**Comment by ggilder** [comment]
Hmm, it doesn't "limit" the name, it just doesn't line everything up any more if you have a name longer than 20 characters. In any case, would you be interested in putting together a patch for this?

**Comment by jszwedko** [comment]
Sorry, I should have been clearer -- yeah, it's just the command descriptions don't line up for commands whose name is longer than 20 characters (we discovered this using the "subcommand" pattern discussed here: https://github.com/tj/commander/issues/52).

I'll take a crack at a patch.

**Comment by ggilder** [comment]
This issue was moved to commander-rb/commander#8
